//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.15 at 04:10:56 AM MSK 
//


package by.kastsiuchenka.third.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for External-parameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="External-parameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="weigth">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="10000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="length" use="required" type="{http://www.example.com/toys}Size" />
 *       &lt;attribute name="width" type="{http://www.example.com/toys}Size" default="0" />
 *       &lt;attribute name="heigth" type="{http://www.example.com/toys}Size" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "External-parameter", propOrder = {
    "weigth"
})
public class ExternalParameter {

    protected int weigth;
    @XmlAttribute(name = "length", required = true)
    protected int length;
    @XmlAttribute(name = "width")
    protected Integer width;
    @XmlAttribute(name = "heigth")
    protected Integer heigth;

    public ExternalParameter(int weigth, int length, Integer width, Integer heigth) {
        this.weigth = weigth;
        this.length = length;
        this.width = width;
        this.heigth = heigth;
    }

    /**
     * Gets the value of the weigth property.
     * 
     */
    public int getWeigth() {
        return weigth;
    }

    /**
     * Sets the value of the weigth property.
     * 
     */
    public void setWeigth(int value) {
        this.weigth = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWidth() {
        if (width == null) {
            return  0;
        } else {
            return width;
        }
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

    /**
     * Gets the value of the heigth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHeigth() {
        if (heigth == null) {
            return  0;
        } else {
            return heigth;
        }
    }

    /**
     * Sets the value of the heigth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeigth(Integer value) {
        this.heigth = value;
    }

}
