//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.12 at 03:11:18 AM MSK 
//


package by.kastsiuchenka.third.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "Type-control")
@XmlEnum
public enum TypeControl {

    MANUAL,
    RADIO,
    ELECTRICAL;


    public static TypeControl fromValue(String v) {
        return valueOf(v);
    }

}
